[program:laravel-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/pbn_automation_software/artisan queue:work database --sleep=3 --tries=3 --max-time=3600 --queue=campaigns,deletions,sidebar_campaigns,scheduled_campaigns,scheduled_sidebar_campaigns,wp_scheduled_campaigns,wp_scheduled_sync,schedule_campaign_bulk_updates,schedule_campaign_deletions,schedule_sidebar_bulk_updates,schedule_sidebar_deletions,wp_scheduled_campaign_bulk_updates,wp_scheduled_campaign_deletions,domainCheck,plugin_deployments,bulk_updates,bulk_blogroll_updates,sidebar_deletions,hidden_links_campaigns,update_hidden_links,delete_hidden_links,delete_hidden_links_campaign,bulk_retry,bulk_retry_sidebar_campaigns,bulk_retry_scheduled_campaigns,bulk_retry_scheduled_sidebar_campaigns,bulk_retry_hidden_links_campaigns,article_permanent_purge,default
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
user=www-data
numprocs=2
redirect_stderr=true
stdout_logfile=/var/www/pbn_automation_software/storage/logs/worker.log
stopwaitsecs=3600
